### ISSUE TITLE
Migrate from Travis CI to GitHub Actions

### ISSUE THREAD

**Issue by mbrukman** [steveniemitz/littletable#7]
FYI, https://travis-ci.org/steveniemitz/littletable now has the following header:

> Since June 15th, 2021, the building on `travis-ci.org` is ceased. Please use `travis-ci.com` from now on.

Thus, unless you have a paid plan with Travis CI, or intend to [file a regular request to re-enable CI for this open-source project][new-travis-billing-model]<sup>1</sup>, it may be time to migrate to GitHub Actions. I've migrated multiple projects from Travis CI to GitHub Actions recently for multiple languages; happy to help migrate this one if you're open to it — let me know!

[new-travis-billing-model]: https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

----

<sup>1</sup> The blog post linked above says:

> * We will be offering an allotment of OSS minutes that will be reviewed and allocated on a case by case basis. Should you want to apply for these credits please open a request with Travis CI support stating that you’d like to be considered for the OSS allotment.

This implies a recurring need to re-apply for build minutes allotment, which may or may not be approved.

**Comment by steveniemitz** [comment]
fixed in 1be198a776234cc0e19e949cf82e18b4508fc30d
